#!/bin/sh
# amalgamate.sh -- emit a single translation unit containing all of doot (D045).
#
# The output is built with `cc -O2 -o doot build/doot.c` and nothing else, which
# is how doot is distributed and how D035 stays a tested property rather than an
# aspiration. Header include guards make the include order safe, so this needs no
# dependency graph.
#
# usage: tools/amalgamate.sh [output]

set -eu

out="${1:-build/doot.c}"
root="$(cd "$(dirname "$0")/.." && pwd)"
rev="$(cd "$root" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"

mkdir -p "$(dirname "$out")"

# Ordered by layer, not alphabetically: base, then the layers above it. Each unit
# includes the headers it needs, so this order is for readability of the output.
units="
src/base/assert.c
src/base/arena.c
src/base/slice.c
src/base/buf.c
src/base/source.c
src/base/diag.c
src/lex/token.c
src/lex/lex.c
src/cli/main.c
"

{
  echo "/* doot $rev -- generated by tools/amalgamate.sh; do not edit."
  echo " *"
  echo " * A single translation unit containing the whole project. Build with:"
  echo " *   cc -O2 -o doot $(basename "$out")"
  echo " */"
  echo
  echo "#ifndef DOOT_BUILD_REV"
  echo "#define DOOT_BUILD_REV \"$rev\""
  echo "#endif"
  echo

  for u in $units; do
    if [ ! -f "$root/$u" ]; then
      echo "amalgamate: missing $u" >&2
      exit 1
    fi
    echo "/* ==== $u ==== */"
    echo "#include \"$root/$u\""
    echo
  done
} >"$out"

# Every .c under src/ must be listed, or the amalgamation would silently omit
# code that the incremental build compiles.
missing=""
for f in $(cd "$root" && find src -name '*.c' | sort); do
  case "
$units" in
  *"
$f
"*) ;;
  *) missing="$missing $f" ;;
  esac
done
if [ -n "$missing" ]; then
  echo "amalgamate: these sources are not in the unit list:$missing" >&2
  exit 1
fi

echo "wrote $out"
